language: c
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script:
- make -C ./Release all
deploy:
  provider: releases
  api_key:
    secure: ya+0YFFBrzAqntAAQEoaNUvGAzdWyQyYcf+0GkAZiNfSevh37SD0iuKjV3HDevYLX2EDqA5bUbtZPRRwQMq2+r/LWwh1jgKjIGW8yAO5IYonJNnlv6SkyHXH+fkSnhpRWo6vd1dy+NijXc7C1MlmlNFJ4kvc4103WH3v5fYoBYAGobzm5V9vqys3Fuk9UzOdnIFhvlE7QLHnZ16GTfD3ZCOQwWOVAC5+XbVc67qcec480utm34SEndUAxITQF2aj0l/6C87Drh1ZrVUXEEE4/qpOOUa0VowleRjEJGeVwhgnh9oEmbYqNzFwHd8rMR8ZLIq2Goa80g5K0gscZPSD6NpxEY0zpH7GwePH4TDNchelIq+fFDGWQMaSbP61pu07je/tql5EcBP1XGxouH4cba+zBW6yjCTfSNPlLoZRXUQeS798hPp6aTve6bIQRQCrbBcwc3lUi7uyFPJkZZpdeRGlLlztsjPusgk7cs65CF6znPRm8TUM8TL/3jPi3dEuTCuai8k9a2Ou40VXSpbUM5cux3G8uyYR5GfNaFHF5RqoqPGeN0Y01n60jshTuXs8S8gAwNC3R5k1g2Bd+B/3q7QcgapEnpojzIB1us9heTDYTgu+sIKLtx0I2oyINo86St/cUVxEHKji6YGrtqUIKLAqMcvoSHJtjBnCEVgi++o=
  file:
  - "Release/Buffalo-3-SE-Pro-OB.hex"
  skip_cleanup: true
  on:
    repo: twistedpearaudio/Buffalo-III-SE-Pro-On-Board-Firmware
    tags: true
    